### ISSUE TITLE
Change to enrol type plugin

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-enrol_course_tokens#16]
# Work plan

- [x] Rename repo to moodle-enrol_course_tokens
- [ ] Make it an enrol type plugin
  - [x] In version.php use enrol_course_tokens
  - [x] Implement enrol_course_tokens_enrol_user($enrol, $user, $roleid): For enrolling a user. will throw exception because students can only be enrolled using the plugin's own activate page.
  - [x] Implement enrol_course_tokens_unenrol_user($enrol, $user): For unenrolling a user. will throw exception because students can only be enrolled using the plugin's own activate page.
  - [x] After those three steps above, confirm that in the admin UI for a course you will see "course_token" as an enrol type you can activate. (If not, use the Moodle plugin skeleton creator to help make a new enrol plugin and study that)
- [x] When creating a token from course token admin page, only allow to select courses which have the course_tokens enrol method activated (currently all courses are shown) you can find this using `SELECT * from mdl_enrol JOIN mdl_courses ... WHERE mdl_enrol.enrol = "course_tokens"`
- [x] When creating a course token, this will associate with mdl_enrol instead of as current mdl_course
- [x] #32

**Comment by fulldecent** [comment]
Hi @Raza403 can you please see this?

This should be a clear plan for making our plugin into an official "enrol" plugin that we will need

**Comment by Raza403** [comment]
course_token enrollment type.

**Comment by Raza403** [comment]
Experiment: Enrolled local plugin, Enrolled enrol using tokens, delete local plugin, see if users enrolled using local plugin still enrolled.
