### ISSUE TITLE
Update user interface of course tokens view.php.

### ISSUE THREAD

**Issue by Raza403** [fulldecent/moodle-enrol_course_tokens#27]
We need to show the progress or status of course tokens. like AHA.
<img width="771" alt="Screenshot 2024-10-30 at 8 26 23 PM" src="https://github.com/user-attachments/assets/73585e08-dbdc-48a8-b9bb-fbd5e49773c7">

**Comment by fulldecent** [comment]
# Work plan

- [ ] Implement this table ^^
- [ ] The assign button will go to assign just one course, like today
- [ ] Add a new note above the table, if the user is not enrolled in any courses then show "You can enroll yourself or somebody else your available inventory of courses. Please click the ASSIGN button below."

# Later

- [ ] Update the assign course button to go to a page that can assign many courses at a time
- [ ] In addition to summary, can also see details of each course used (page and CSV download)

**Comment by fulldecent** [comment]
Discussed today, Ahmed is ready to go, not needing anything to start

**Comment by Raza403** [comment]
When a person is enrolled, the token is assigned.
When any activity like read material or exam is completed, this is in progress.
We will have a completion condition for each course, means complete.
Failing an exam is fail. In the case of AHA courses, we don't have exam, so no fail.

**Comment by honeylaroza** [comment]
in the course token dashboard, it needs to add just a "status" column where the student's recent activity is shown 
![image](https://github.com/user-attachments/assets/d49c60d0-fd7e-4164-9786-160df10f477b)


and then make a separate report like the AHA dashboard that we talked about last time for product - course inventory

![image](https://github.com/user-attachments/assets/c79640bf-e1ca-40e1-8b44-50aa2f6c460f)

**Comment by Raza403** [comment]
This is how view_tokens.php looks like now.
<img width="1438" alt="Screenshot 2024-12-01 at 10 17 51 AM" src="https://github.com/user-attachments/assets/87fb6ba5-6254-484e-9fd6-f07a8bb8e5f2">

**Comment by Raza403** [comment]
<img width="1436" alt="Screenshot 2024-12-02 at 7 49 28 PM" src="https://github.com/user-attachments/assets/23dcb11e-fe13-4424-ae83-7a73f9988f33">
