### ISSUE TITLE
Validate email input, suggest hints, suggest autocomplete

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-enrol_course_tokens#45]
When assigning a token you must input an email address.

This invites the chance of a email address typo. Each such typo will result in customer pain and very likely us getting a phone call.

---

Let's add JavaScript to the page so that email input will show:

- An error if the email address is invalid
- A hint if we suspect the email address has a typo

---

# Work plan

Email input is VERY IMPORTANT, it is the \#2 contributor to customer support issues.

Please carefully review, and think about any progress we can make on this issue.

You can make any progress on this today and merge in improvements over time as features are complete.

- [ ] Create a flow chart for what happens for each key press (keyup, keypress, paste from clipboard).
- [ ] Create a flow chart for what happens after focus leaves the input box.
- [ ] Solve one thing below.
- [ ] Document it.
  - [ ] With text, in the README
  - [ ] Video for each thing, shown in GitHub
- [ ] Ship it.
- [ ] Repeat. ^^^
- [ ] Video documentation of the system as a whole, quickly going through a few scenarios, added to README as a GIF (can do that last when all done)

# Requirements/test cases

All test cases related to typing in an email address into the assign token page. This is a very important page.

Each test case is happening during each key press. It shall not be necessary to end focus on the field for the test case to begin.

## Basic autocomplete

1. Type `bob@g`.

- [ ] Expect: Recommend the auto complete `bob@gmail.com`.

Note: Because `gmail` is the most popular email domain starting with `g`.

## Autocomplete to same custom domain

1. Login as user with email address `mary@abc.com`.
2. abc.com is not on a public list of popular email domains.
3. Type `steve@`.

- [ ] Expect: Recommend `steve@abc.com`.

Note: Because this user has a custom email address that is not a common email address, we expect that when they send a token that they will send it to a coworker sharing their same email domain.

1. Continuing as per above, then type `b` to get `steve@b`.

- [ ] Expect: Remove the recommendation `steve@abc.com` because `@b` does not follow to `@abc`.

1. Continuing as per above, then type `b` to get `steve@a`.

- [ ] Expect: Keep the recommendation `steve@abc.com` because `@a` does follow to `@abc`.

## Show errors for partial invalid email addresses

1. Type `steve@@`

- [ ] Expect: Show that this email address is invalid.

This partially-typed email address is prima facie of an error. There is no possible way to continue typing and produce a valid email address.

## Show errors for a complete invalid email address

1. Type `steve@example`
2. Press tab or otherwise leave the editing for that field.

- [ ] Expect: Show that the email address is invalid.

Note: This is an invalid format for an email address. (Use a subset of RF)

Valid addresses are: RFC 5322–compliant email address that use a fully qualified domain name (FQDN) and can be delivered over the public internet.

## Show warnings for known bad email addresses (online lookup)

We maintain records of email addresses that are bad (customer emails that previously hard bounced, etc.)

When doing this email input, this is a good opportunity to warn about the potential problem.

This will hook into a separate system for online lookup on our private database of email addresses.

But this is an open source project so we will build this in a modular way and mock the other half of the connection.

1. Create a PHP file which
   1. Checks the `?email=XXX` query parameter
   2. If the email is `error@example.com` return status 200 with `{"status": "error", "note": "This is a known bad email address."}`.
   3. If the email is `warning@example.com` return status 200 with `{"status": "warning", "note": "This is probably a bad email address."}`.
   4. If the email is `good@example.com` return status 200 with `{"status": "good"}`.
   5. Otherwise it returns `{"status": "unknown"}`.
2. Create a admin setting/config page for this plugin (see moodle-local_template for an example of adding a settings page). 
3. On the settings page you may edit the email validator URL, you may enter a bearer authorization header token (optional), you may turn this feature on or off
   1. There is a note that URL must return JSON in one of these format:
      1. `{"status": "error", "note": "This is a full sentence explaining why this is an error and what could be wrong."}` 
         1. Error will show to visitor. Sending the form will not be permitted.
      2.  `{"status": "warning", "note": "This is a full sentence explaining to the visitor why this is a warning and what could be the problem."}`
         1. Warning will show to visitor. Sending will still be permitted.
      3. `{"status": "unknown"}` . Other processing will be done by the `PLUGIN NAME` and warnings/errors shown as appropriate.
      4.  `{"status": "good"}` this is a known good address. And client side checking (warnings/errors) will not be shown.
   2. There is a note that the URL will be called with an additional `?email=...` query param
      1. This must work for urls like `a.php` (loads `a.php?email=...`)
      2. This must work for urls like `a.php?a=b` (loads `a.php?a=b&email=`, note)
   3. There is a note that only complete (not partial typing) email addresses will be sent to the API route. And known bad (invalid format, e.g. `bob@@@~~!~nthoe`) will be reported immediately and not sent to API route.
   4. Default on/off status is OFF
   5. Default script URL is the URL of the mock script.
4. There is a separate API route which is authenticated (Moodle logged in, any user) and this route only proxies the external API callback (the external callback URL is private and frontend client will not see it)

Test case:

1. Turn admin setting to OK and use the default URL.
2. Enter email address `error@example.com` .
3. Leave focus from the email field.

- [ ] API request is sent to the mock script.
- [ ] A error (styled as an error) is shown  `This is a full sentence explaining why this is an error and what could be wrong.`

1. Enter email address `warning@example.com` .
2. Leave focus from the email field.

- [ ] API request is sent to the mock script.
- [ ] A warning (styled as a warning) is shown `This is a full sentence explaining to the visitor why this is a warning and what could be the problem.`

Follow on work:

- [ ] Will to implement that external API route on API server
  - [ ] Check bounced emails from Mandrill database.
  - [ ] Check old email addresses, where customer changed their email address. (Warning.)
  - [ ] Maybe? check similar email addresses (one or two characters different than a known email address.)
  - [ ] Otherwise return `unknown`
  - [ ] LATER, think about returning GOOD, this would be a security risk of allowing lookup of our customer email addresses, maybe do logging and think about this risk and how helpful it would be.
- [ ] Update spec above to also allow including recommended email addresses in the response. `"recommendations": ["a@b.c", ...]`

## Easy selection of hints

When hint is available, it should be possible to select and implement that hint using a variety of clicks or key presses that are intuitive.

This must work well on mobile and desktop browsers.

Ensure that any hints will be visible in the viewport. If the email input is scrolled to the bottom of the page, then the availability of hints must be visible (by scrolling up a bit).

## User testing

The solution here must be tested and endorsed by Deb, Honey, Heidi AND Terry.

Testing shall be done by screen share using a desktop computer. (Video recorded. Attach all videos to this issue.)

Additionally testing shall be done by using a computer to record video but the tester will be using a mobile phone. Position the phone in the video frame so we can watch exactly how they use it. (Record video, attach videos to this issue.)

# Notes

This will require some testing and trials to get it right.

Please deploy to test server or other place that other team members can use.
